#!/bin/bash

BLUE='\033[0;34m'
RESET='\033[0m'

print_script_name() {
    echo -e "\n${BLUE}=== Installing $(basename "$0" | sed 's/install-//') ===${RESET}\n"
}

print_done() {
    echo -e "\n${BLUE}=== Done ===${RESET}\n"
}
