#!/bin/bash

source ../snippets/bash/decorator

print_script_name

sudo apt install -y software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible
sudo apt install -y python3-argcomplete
sudo register-python-argcomplete3 --global

print_done
