#!/bin/bash

set -e

source ../snippets/bash/decorator
source ../snippets/bash/tempdir

print_script_name
temp_dir

VERSION=""
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


clean_temp
print_done
