#!/bin/bash

set -e

source ../snippets/bash/decorator
source ../snippets/bash/tempdir

print_script_name
temp_dir

APP="terraform"
VERSION="1.11.3"

curl -L https://releases.hashicorp.com/"${APP}"/"${VERSION}"/${APP}_${VERSION}_linux_amd64.zip -o "${APP}".zip

file "${APP}"*

unzip "${APP}".zip

chmod +x "${APP}"

sudo mv "${APP}" /usr/local/bin/

clean_temp
print_done


#https://releases.hashicorp.com/terraform/1.11.3/terraform_1.11.3_linux_amd64.zip
