#!/usr/bin/env bash

_have() { type "$1" &>/dev/null; }

#declare ANTHROPIC_API_KEY
#ANTHROPIC_API_KEY="$(tail -n2 "$HOME/.config/gpt/token")"
#export ANTHROPIC_API_KEY

#declare OPENAI_API_KEY
#OPENAI_API_KEY="$(head -1 "$HOME/.config/gpt/token")"
#export OPENAI_API_KEY

declare GROQ_API_KEY
GROQ_API_KEY="$(tail -n1 "$HOME/.config/gpt/token")"
export GROQ_API_KEY

! _have mods && echo "requires charmbracelet/mods" && exit 1

#if test -t 0; then
#  if _have glow; then
#    mods --status-text "Ummm" -f "$*" | glow
#  else
   #mods -m gemma2 -f --status-text "Ummm" "$*" # --settings to see aliases
    mods -m gemma2 -f --status-text "Ummm" "$*" # --settings to see aliases
#   mods -m claude3.5-sonnet -f --status-text "Ummm" "$*"
#  fi
#else
#  mods --quiet "$*" | sed -E 's,[?25l [0D[2K[?25h[?1002l[?1003l,,g'
  # |sed 's/\x1B\[[0-9;\?]*[a-zA-Z]//g'
#fi

# https://console.groq.com/settings/limits

