#!/usr/bin/env bash

declare -A emoji
emoji[xx]=❌
emoji[check]=✅
emoji[todo]=⬛
emoji[?]=❓
emoji[block]=🚫
emoji[ongoing]=🔄
emoji[smile]=😃
emoji[idea]=💡
emoji[stop]=🛑
emoji[warning]=⚠️
emoji[tux]=🐧
emoji[leftarrow]=←
emoji["<--"]=←
emoji[rightarrow]=→
emoji["-->"]=→
emoji[poop]=💩
emoji[facepalm]=🤦

toemoji() {
	local in=/dev/stdin
	local out=/dev/stdout
	local file="$1"
	if [[ -n $file ]]; then
		in="$file"
		out="$(mktemp)"
	fi
	IFS=$'\n'
	while read -r line; do
		for k in "${!emoji[@]}"; do
			line=${line//:$k:/${emoji[$k]}}
			[[ $line =~ ^--- ]] && continue
			line=${line//---/—}
			line=${line//--\>/→}
			line=${line//:bullet:/•}
		done
		echo "$line" >>"$out"
	done <"$in"
	if [[ -n $file ]]; then
		cp "$out" "$file"
		rm "$out"
	fi
}

toemoji "$@"
